module.exports = [
  '',
  'Formula',
  'Crystal Data',
  'Physical Properties',
  'Optical Properties',
  'Cell Data',
  'X-ray Powder Pattern',
  'X-Ray Diffraction Pattern',
  'Chemistry',
  'Occurrence',
  'Association',
  'Distribution',
  'Name',
  'Type',
  'Material',
  'Type Material',
  'References',
];
